---

# Installation tasks

- name : Import aptly GPG key
  become : True
  apt_key :
    id : "{{ aptly_gpg_key }}"
    keyserver : "{{ aptly_gpg_keyserver }}"
    state : 'present'

- name : Install aptly repository
  become : True
  apt_repository :
    repo : "{{ aptly_repository }}"
    update_cache : True
    state : 'present'

- name : Create aptly user
  become : True
  user :
    name : "{{ aptly_user }}"
    comment : 'User for aptly repository management'
    home : "{{ aptly_user_home }}"
    shell : '/bin/bash'

- name : Change home permission
  become : True
  file :
    dest : "{{ aptly_user_home }}"
    mode : '0700'

- name : Install aptly package
  become : True
  apt :
    name : "{{ item }}"
    cache_valid_time : 3600
    update_cache : True
    state : 'present'
  with_items: "{{ aptly_packages }}"

